# Generated by Django 5.0.4 on 2025-04-13 02:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fuelstation", "0002_rename_station_fueltank_fuel_station_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPerformanceStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_dispatches", models.IntegerField(default=0)),
                ("completed_on_time", models.IntegerField(default=0)),
                ("delayed_deliveries", models.IntegerField(default=0)),
                ("cancelled_deliveries", models.IntegerField(default=0)),
                (
                    "average_dispatch_time",
                    models.IntegerField(help_text="Koha mesatare në minuta"),
                ),
            ],
            options={
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("FUEL_CONSUMPTION", "Konsumi i Karburantit"),
                            ("DELIVERY_EFFICIENCY", "Efiçenca e Dërgesave"),
                            ("VEHICLE_USAGE", "Përdorimi i Automjeteve"),
                            ("STATION_INVENTORY", "Inventari i Stacioneve"),
                            ("CUSTOM", "Raport i Personalizuar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Parametrat e përdorur për gjenerimin e raportit",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_generated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_scheduled", models.BooleanField(default=False)),
                (
                    "schedule_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Çdo ditë"),
                            ("WEEKLY", "Çdo javë"),
                            ("MONTHLY", "Çdo muaj"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("chart_config", models.JSONField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_sets",
                        to="analytics.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuelConsumptionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("GASOLINE_95", "Gasoline 95"),
                            ("GASOLINE_98", "Gasoline 98"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "quantity_delivered",
                    models.IntegerField(
                        default=0, help_text="Sasia e dorëzuar në litra"
                    ),
                ),
                (
                    "quantity_sold",
                    models.IntegerField(default=0, help_text="Sasia e shitur në litra"),
                ),
                (
                    "fuel_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumption_stats",
                        to="fuelstation.fuelstation",
                    ),
                ),
            ],
            options={
                "unique_together": {("fuel_station", "fuel_type", "date")},
            },
        ),
    ]
