# Generated by Django 5.0.4 on 2025-03-18 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fuelstation", "0001_initial"),
        ("truck", "0002_alter_compartment_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_date", models.DateTimeField()),
                ("arrival_date", models.DateTimeField(blank=True, null=True)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planifikuar"),
                            ("IN_PROGRESS", "Në Proces"),
                            ("COMPLETED", "Përfunduar"),
                            ("CANCELLED", "Anuluar"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_dispatches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fuel_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="fuelstation.fuelstation",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="truck.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_type", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(help_text="Sasia në litra")),
                ("loaded", models.BooleanField(default=False)),
                ("delivered", models.BooleanField(default=False)),
                (
                    "compartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="truck.compartment",
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loads",
                        to="dispatch.dispatch",
                    ),
                ),
            ],
        ),
    ]
