# Generated by Django 5.0.4 on 2024-04-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        help_text="License plate number", max_length=20, unique=True
                    ),
                ),
                (
                    "chassis_number",
                    models.CharField(
                        help_text="Chassis number", max_length=50, unique=True
                    ),
                ),
                (
                    "compartment_number",
                    models.IntegerField(help_text="Number of compartments"),
                ),
                (
                    "separated_cab",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the cab is separated from the tank",
                    ),
                ),
                (
                    "has_pump",
                    models.BooleanField(
                        default=False, help_text="Whether it has a pump"
                    ),
                ),
                (
                    "hose_length",
                    models.IntegerField(
                        blank=True, help_text="Hose length in meters, if any", null=True
                    ),
                ),
                (
                    "free_flow_unloading",
                    models.BooleanField(
                        default=False, help_text="Whether it unloads by free flow"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Capacity in liters of the compartment"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compartments",
                        to="truck.vehicle",
                    ),
                ),
            ],
        ),
    ]
