# Generated by Django 5.0.4 on 2025-03-18 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("truck", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compartment",
            options={"ordering": ["compartment_number"]},
        ),
        migrations.AddField(
            model_name="compartment",
            name="compartment_number",
            field=models.IntegerField(default=1, help_text="Numri rendor i dhomës"),
        ),
        migrations.AddField(
            model_name="compartment",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Nëse dhoma është aktualisht aktive"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Nëse mjeti është aktualisht aktiv"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_maintenance_date",
            field=models.DateField(
                blank=True, help_text="Data e mirëmbajtjes së fundit", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="next_maintenance_date",
            field=models.DateField(
                blank=True,
                help_text="Data e mirëmbajtjes së ardhshme të planifikuar",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Shënime shtesë për mjetin", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("TANKER", "Autobote"),
                    ("TRUCK", "Kamion"),
                    ("TRAILER", "Rimorkio"),
                ],
                default="TANKER",
                help_text="Tipi i mjetit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="year_of_manufacture",
            field=models.IntegerField(
                blank=True, help_text="Viti i prodhimit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="compartment",
            name="capacity",
            field=models.IntegerField(help_text="Kapaciteti në litra i dhomës"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(
                help_text="Numri i shasisë", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="compartment_number",
            field=models.IntegerField(help_text="Numri i dhomave"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="free_flow_unloading",
            field=models.BooleanField(
                default=False, help_text="Nëse shkarkon me rrjedhje të lirë"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="has_pump",
            field=models.BooleanField(default=False, help_text="Nëse ka pompë"),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="hose_length",
            field=models.IntegerField(
                blank=True, help_text="Gjatësia e tubit në metra, nëse ka", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="license_plate",
            field=models.CharField(
                help_text="Numri i targës", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="separated_cab",
            field=models.BooleanField(
                default=False, help_text="Nëse kabina është e ndarë nga cisterna"
            ),
        ),
    ]
