# Generated by Django 5.0.4 on 2025-03-19 00:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fuelstation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fueltank",
            old_name="station",
            new_name="fuel_station",
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelstation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fueltank",
            name="current_level",
            field=models.IntegerField(
                default=1000, help_text="Current fuel level in liters"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fueltank",
            name="capacity",
            field=models.IntegerField(help_text="Capacity in liters"),
        ),
        migrations.AlterField(
            model_name="fueltank",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("DIESEL", "Diesel"),
                    ("GASOLINE_95", "Gasoline 95"),
                    ("GASOLINE_98", "Gasoline 98"),
                ],
                max_length=20,
            ),
        ),
    ]
