# Generated by Django 5.0.4 on 2025-04-13 02:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("fuelstation", "0002_rename_station_fueltank_fuel_station_and_more"),
        ("truck", "0002_alter_compartment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimated_distance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distanca në kilometra",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        help_text="Kohëzgjatja e parashikuar në minuta"
                    ),
                ),
                (
                    "actual_duration",
                    models.IntegerField(
                        blank=True, help_text="Kohëzgjatja faktike në minuta", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planifikuar"),
                            ("IN_PROGRESS", "Në Progres"),
                            ("COMPLETED", "Përfunduar"),
                            ("CANCELLED", "Anuluar"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                (
                    "route_data",
                    models.JSONField(
                        blank=True, help_text="Të dhënat e rrugës nga API", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route",
                        to="dispatch.dispatch",
                    ),
                ),
                (
                    "end_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_as_end",
                        to="fuelstation.fuelstation",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_as_start",
                        to="fuelstation.fuelstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteWaypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stop_time",
                    models.IntegerField(
                        default=0, help_text="Koha e ndalimit në minuta"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="tracking.route",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VehicleLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "altitude",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                (
                    "speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Shpejtësia në km/h",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Drejtimi në gradë",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="truck.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
